import Link from "next/link";

const SECTIONS = [
  {
    title: "Acceptance of terms",
    body: (
      <p>
        By creating an account or using Résona, you agree to these terms. Résona is provided as a
        portfolio project demonstrating an AI-powered resume and job-match analysis product, not a
        commercial service with guaranteed uptime or support SLAs.
      </p>
    ),
  },
  {
    title: "Description of service",
    body: (
      <p>
        Résona analyzes your resume against a job description to produce a match score, identify
        matching and missing skills, rewrite resume sections, and generate cover letters. These
        outputs are generated by third-party AI models (Groq, HuggingFace) and are provided for
        your convenience.
      </p>
    ),
  },
  {
    title: "AI-generated content disclaimer",
    body: (
      <p>
        Match scores, gap analysis, rewrites, and cover letters are AI-assisted suggestions. They
        are not guaranteed to be accurate, complete, or effective, and should be reviewed and
        edited before you use them in a real job application. Résona makes no guarantee about
        interview or hiring outcomes.
      </p>
    ),
  },
  {
    title: "Your content",
    body: (
      <p>
        You retain full ownership of the resume content and job descriptions you submit. We do not
        claim any intellectual property rights over content you upload, and we only process it to
        provide the analysis features described in this document and in our{" "}
        <Link href="/privacy" className="text-accent hover:underline">
          Privacy Policy
        </Link>
        .
      </p>
    ),
  },
  {
    title: "Subscription & billing",
    body: (
      <p>
        Résona offers a Free plan with limited monthly analyses and a Pro plan with unlimited
        analyses, section rewriting, and cover letter generation. Pro subscriptions are billed
        through Stripe and can be cancelled at any time from your billing settings; access
        continues until the end of the current billing period.
      </p>
    ),
  },
  {
    title: "Acceptable use",
    body: (
      <p>
        You agree not to use Résona to upload unlawful content, attempt to circumvent rate limits
        or usage quotas, or interfere with the service&apos;s normal operation.
      </p>
    ),
  },
  {
    title: "Limitation of liability",
    body: (
      <p>
        The service is provided &quot;as is&quot; without warranty of any kind, express or implied.
        Résona and its author are not liable for any damages arising from your use of the service,
        including decisions made based on AI-generated analysis or content.
      </p>
    ),
  },
  {
    title: "Termination",
    body: (
      <p>
        We may suspend or terminate access to accounts that violate these terms. You may stop
        using Résona and request account deletion at any time.
      </p>
    ),
  },
  {
    title: "Changes to these terms",
    body: (
      <p>
        We may update these terms as the product evolves. Material changes will be reflected here
        with an updated date.
      </p>
    ),
  },
];

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl px-5 py-16 md:px-16">
      <h1 className="font-display text-2xl font-bold text-base-light">Terms of Service</h1>
      <p className="mt-2 text-xs tracking-widest text-muted uppercase">Last updated: 2026-07-20</p>

      <p className="mt-8 text-sm leading-relaxed text-muted">
        These terms govern your use of Résona. As with our{" "}
        <Link href="/privacy" className="text-accent hover:underline">
          Privacy Policy
        </Link>
        , we&apos;ve kept this in plain language rather than dense legal text.
      </p>

      {SECTIONS.map((section) => (
        <section key={section.title} className="mt-10">
          <h2 className="mb-3 font-display text-lg font-medium text-base-light">{section.title}</h2>
          <div className="text-sm leading-relaxed text-muted">{section.body}</div>
        </section>
      ))}

      <p className="mt-10 text-sm text-muted">
        Questions about these terms?{" "}
        <a href="mailto:hello@resona.dev" className="text-accent hover:underline">
          hello@resona.dev
        </a>
      </p>
    </div>
  );
}
